#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor -d I II III IV V VI VII VIII IX X
# bspc monitor -d I II III IV V

bspc monitor -d 一 二 三 四 五 六
#bspc monitor HDMI-0 -d I II III IV V
#bspc monitor VGA-1 -d VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           1
bspc config top_padding         70
bspc config bottom_padding      70
bspc config left_padding        70
bspc config right_padding       70

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

# /home/edu/.config/polybar/launch.sh &
# /home/edu/.config/polybar/launch.sh one &
# /home/edu/.config/polybar/launch.sh long &
/home/edu/.config/polybar/launch.sh min &
#/home/edu/.config/Scripts/wall.sh &
picom -b &
setxkbmap br &
xset s off &
xset -dpms &
feh --bg-fill /home/edu/img/wall/leafs.jpg &
