
code_syntax_highlight = "onedark"

# border
file_panel_border = "#222222"
sidebar_border = "#222222"
footer_border = "#222222"

# border active
file_panel_border_active = "#777777"
sidebar_border_active = "#777777"
footer_border_active = "#777777"
modal_border_active = "#777777"

# background (bg)
full_screen_bg = "#0c0c0c"
file_panel_bg = "#0c0c0c"
sidebar_bg = "#0c0c0c"
footer_bg = "#0c0c0c"
modal_bg = "#0c0c0c"

# foreground (fg)
full_screen_fg = "#777777"
file_panel_fg = "#777777"
sidebar_fg = "#777777"
footer_fg = "#777777"
modal_fg = "#777777"

# special color
cursor = "#dddddd"
correct = "#47ef7d"
error = "#d70000"
hint = "#5bd9f3"
cancel = "#6575ab"
gradient_color = ["#720000", "#ff0000"]

# file panel special items
file_panel_top_directory_icon = "#dddddd"
file_panel_top_path = "#777777"
file_panel_item_selected_fg = "#777777"
file_panel_item_selected_bg = "#0c0c0c"

# sidebar special items
sidebar_title = "#777777"
sidebar_item_selected_fg = "#777777"
sidebar_item_selected_bg = "#0c0c0c"
sidebar_divider = "#615250"

# modal special items
modal_cancel_fg = "#f9f9fe"
modal_cancel_bg = "#000042"

modal_confirm_fg = "#f9f9fe"
modal_confirm_bg = "#ffb86c"

# help menu
help_menu_hotkey = "#ff8d34"
help_menu_title = "#ff6666"
